# -*- coding: utf-8 -*-
"""basiclevelq.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AW43JcQ5WdIiuoXf7dTVupOQo6XudJWs
"""

x=5
y=3.2
z="hello"
print(x+y)
print(z+"wolrd")

defis_even(num):
  return num%2==0
  num=3
  print(num)

result=10%3
print(result)

x=True
y=False
res=x and y
print(res)

a=5
a+=3
print(a)

geeting="hello" + "world"
print(geeting)

res="python"*3
print(res)

num=int("42")+8
print(num)

res=17//4
print(res)

a=7
b=5
c=a != b
print(c)

