# -*- coding: utf-8 -*-
"""listq.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GV6TZ_jaJnnzShwh768sTpYfSEMol0h4
"""

A=[1,2,3.8,4,5,7,'apple',3,4,6,8,'b']
print(A[1:8:1])

print(A[-1:-6:-3])

print(A[-1:-6:3])

print(A[-6:-1:-2])

print(A[-6:-1:2])

