# -*- coding: utf-8 -*-
"""pattern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zTYvwFqzFuEa_aKNaI5dUnxXyYe8Wssx
"""

#1right tirngel
a=5
for i in range(0,a):
  for j in range(0,i+1):
    print("*",end=" ")
  print()

# left tirangle
a=6
for i in range(0,a):
  for j in range(i,a):
    print(" ",end=" ")
  for k in range(0,i):
    print("*",end=" ")
  print()

#2 triangle
a=5
for i in range(1,a+1):
  for j in range(a-i):
    print(" ",end=" ")
  for k in range(1,2*i):
    print("*",end=" ")
  print()

#3 square
a=5
for i in range(a):
  for j in range(a):
    print("*",end=" ")
  print()

#4hollow square
a=6
for i in range(1,a+1):
  for j in range(1,a+1):
    if 1==i or 1==j or i==a or j==a:
      print("*",end=" ")
    else:
      print(" ",end=" ")
  print()

#5pyramid
a=5
for i in range(1,a+1):
  for j in range(a-i):
    print(" ",end="")
  for k in range(1,2*i):
    print("*",end="")
  print()

#6dimanond
for i in range(1,a+1):
  for j in range(a-i):
    print(" ",end="")
  for k in range(1,2*i):
    print("*",end="")
  print()
for i in range(a-1,0,-1):
  for j in range(a-i):
    print(" ",end="")
  for k in range(1,2*i):
    print("*",end="")
  print()

#7 number
a=5
for i in range(0,a):
  for j in range(0,i+1):
    print(i,end=" ")
  print()

#8 fibonacci number
a=5
for i in range(0,a):
  for j in range(0,i+1):
    print(j,end=" ")
  print()

#9 inverted
for i in range(a-1,0,-1):
  for j in range(a-i):
    print(" ",end="")
  for k in range(1,2*i):
    print("*",end="")
  print()

#10 custom
for i in range(1,a+1):
  for j in range(1,a+1):
    if 1==i or 1==j or i==a or j==a:
      print("*",end=" ")
    else:
      print(" ",end=" ")
  print()

